version: "3.1"
 
services: 
  gui:
    image: node:16-alpine
    working_dir: /app
    command: "npm run start"
    volumes:
      - ./gui:/app
    ports:
      - 3000:3000
    depends_on:
      - api
  api:
    image: api
    build: ./project-practice-laravelLumen
    working_dir: /var/www/
    volumes:
      - ./api:/var/www/
      - ./api/:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - db
  db:
    image: postgres:12
    env_file: .env
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
